### PR TITLE
Gm 2 models relationships

### PR DESCRIPTION
**Pull request by mwangiowen**

### CODE REVIEW

**Review by JohnMartin-19 — APPROVED** [review]
I have approved the merging

**Comment by amaar7** [comment]
reviwed

**Comment by amaar7** [comment]
reviwed all files

**Comment by jimotieno475** [comment]
Login and Signup Rautes inserted for the Buyer and the Farmer

**Comment by conokisekai** [comment]
The models represent entities such as buyers, farmers, products, reviews, orders, and notifications, with relationships between them for database management

**Comment by faithwest** [comment]
testing routes using thunder client

**Review by khalid0310 — APPROVED** [review]
Add input validation to ensure data integrity and prevent security

**Review by conokisekai — APPROVED** [review]
The models represent entities such as buyers, farmers, products, reviews, orders, and notifications, with relationships between them for database management

**Comment by amaar7** [comment]
reviwed all files

**Review by faithwest — APPROVED** [review]
testing routes using thunder client

**Review by jimotieno475 — APPROVED** [review]
Login and Signup Rautes inserted for the Buyer and the Farmer

**Review by amaar7 — APPROVED** [review]
reviwed all files

**Review by willykibet — COMMENTED** [review]
reviewing all inputs

**Pull request merged**
